  name: MelonOS
  main: MelonOS
  version: ${version}
  author: Meloni
  description: "MelonOS Minecraft Plugin"
  prefix: MelonOS

  commands:
    melonos:
      description: "Main MelonOS command"
      usage: "/melonos"
    test:
      description: "Displays Test"
      usage: "/test"